In [177]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("amitabhajoy/bengaluru-house-price-data")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Nayan\.cache\kagglehub\datasets\amitabhajoy\bengaluru-house-price-data\versions\2

In [178]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [179]:
df = pd.read_csv(r"C:\Users\Nayan\.cache\kagglehub\datasets\amitabhajoy\bengaluru-house-price-data\versions\2\Bengaluru_House_Data.csv")
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [180]:
df.shape

(13320, 9)

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [182]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [183]:
df.area_type.unique()

array(['Super built-up  Area', 'Plot  Area', 'Built-up  Area',
       'Carpet  Area'], dtype=object)

In [184]:
df.availability.unique()

array(['19-Dec', 'Ready To Move', '18-May', '18-Feb', '18-Nov', '20-Dec',
       '17-Oct', '21-Dec', '19-Sep', '20-Sep', '18-Mar', '20-Feb',
       '18-Apr', '20-Aug', '18-Oct', '19-Mar', '17-Sep', '18-Dec',
       '17-Aug', '19-Apr', '18-Jun', '22-Dec', '22-Jan', '18-Aug',
       '19-Jan', '17-Jul', '18-Jul', '21-Jun', '20-May', '19-Aug',
       '18-Sep', '17-May', '17-Jun', '21-May', '18-Jan', '20-Mar',
       '17-Dec', '16-Mar', '19-Jun', '22-Jun', '19-Jul', '21-Feb',
       'Immediate Possession', '19-May', '17-Nov', '20-Oct', '20-Jun',
       '19-Feb', '21-Oct', '21-Jan', '17-Mar', '17-Apr', '22-May',
       '19-Oct', '21-Jul', '21-Nov', '21-Mar', '16-Dec', '22-Mar',
       '20-Jan', '21-Sep', '21-Aug', '14-Nov', '19-Nov', '15-Nov',
       '16-Jul', '15-Jun', '17-Feb', '20-Nov', '20-Jul', '16-Sep',
       '15-Oct', '15-Dec', '16-Oct', '22-Nov', '15-Aug', '17-Jan',
       '16-Nov', '20-Apr', '16-Jan', '14-Jul'], dtype=object)

In [185]:
df.location.unique()

array(['Electronic City Phase II', 'Chikka Tirupathi', 'Uttarahalli', ...,
       '12th cross srinivas nagar banshankari 3rd stage',
       'Havanur extension', 'Abshot Layout'], shape=(1306,), dtype=object)

In [186]:
df['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', nan, '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [187]:
df.society.unique()

array(['Coomee ', 'Theanmp', nan, ..., 'SJovest', 'ThhtsV ', 'RSntsAp'],
      shape=(2689,), dtype=object)

In [188]:
df.total_sqft.unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [189]:
df.bath.unique()

array([ 2.,  5.,  3.,  4.,  6.,  1.,  9., nan,  8.,  7., 11., 10., 14.,
       27., 12., 16., 40., 15., 13., 18.])

In [190]:
df.balcony.unique()

array([ 1.,  3., nan,  2.,  0.])

In [191]:
df.price.unique()

array([ 39.07, 120.  ,  62.  , ...,  40.14, 231.  , 488.  ], shape=(1994,))

In [192]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

checking the %age of null values with the actual values

In [193]:
df[df.society.isnull()==True].shape[0]/df.shape[0]*100

41.306306306306304

In [194]:
df[df.balcony.isnull()==True].shape[0]/df.shape[0]*100

4.572072072072072

In [195]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [196]:
backup = df.copy()
df.drop(columns=['area_type','availability','society','balcony'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [197]:
df.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [198]:
for i in df.select_dtypes(include='object'):
    print(df[i].value_counts())

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64

In [199]:
df.location = df.location.fillna(value='Whitefield')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [200]:
df['size'].mode()[0]

'2 BHK'

In [201]:
df['size'] = df['size'].fillna(value=df['size'].mode()[0])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [202]:
df['bhk'] = df['size'].str.split().str.get(0).astype(int)
df[df.bhk>20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [203]:
df.total_sqft.unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [204]:
a = df['total_sqft'].str.split(' - ')
a

0        [1056]
1        [2600]
2        [1440]
3        [1521]
4        [1200]
          ...
13315    [3453]
13316    [3600]
13317    [1141]
13318    [4689]
13319     [550]
Name: total_sqft, Length: 13320, dtype: object

In [205]:
def ConvertRange(x):
    temp = x.split(' - ')
    if len(temp)==2:
        return (float(temp[0])+(float(temp[1])))/2
    try:
        return float(x)
    except:
        return None

In [206]:
df['total_sqft'] = df['total_sqft'].apply(ConvertRange)

In [207]:
df['PricePerSqFt'] = df['price']*100000/df['total_sqft']

In [208]:
df.head(2)

,location,size,total_sqft,bath,price,bhk,PricePerSqFt
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4615.384615

In [209]:
df.describe()

         total_sqft          bath         price           bhk  PricePerSqFt
count  13274.000000  13247.000000  13320.000000  13320.000000  1.327400e+04
mean    1559.626694      2.692610    112.565627      2.802778  7.907501e+03
std     1238.405258      1.341458    148.971674      1.294496  1.064296e+05
min        1.000000      1.000000      8.000000      1.000000  2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000  4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000  5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000  7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000  1.200000e+07

In [210]:
df.location.value_counts()

location
Whitefield                         541
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [211]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   location      13320 non-null  object
 1   size          13320 non-null  object
 2   total_sqft    13274 non-null  float64
 3   bath          13247 non-null  float64
 4   price         13320 non-null  float64
 5   bhk           13320 non-null  int64
 6   PricePerSqFt  13274 non-null  float64
dtypes: float64(4), int64(1), object(2)
memory usage: 728.6+ KB

In [212]:
df['location'] = df['location'].apply(lambda x:x.strip())
loc_cnt = df.location.value_counts()
loc_cnt

location
Whitefield                              542
Sarjapur  Road                          399
Electronic City                         304
Kanakpura Road                          273
Thanisandra                             237
                                       ...
Duddanahalli                              1
Doddanakunte                              1
Jogupalya                                 1
Subhash Nagar                             1
Kengeri Satellite Town KHB Apartment      1
Name: count, Length: 1294, dtype: int64

In [213]:
loc_cnt_less10 = loc_cnt[loc_cnt<=10]
loc_cnt_less10

location
Basapura                                10
Dairy Circle                            10
Nagappa Reddy Layout                    10
Naganathapura                           10
Sector 1 HSR Layout                     10
                                        ..
Duddanahalli                             1
Doddanakunte                             1
Jogupalya                                1
Subhash Nagar                            1
Kengeri Satellite Town KHB Apartment     1
Name: count, Length: 1053, dtype: int64

In [214]:
df.location = df.location.apply(lambda x:'other' if x in loc_cnt_less10 else x)
df.location.value_counts()

location
other                        2885
Whitefield                    542
Sarjapur  Road                399
Electronic City               304
Kanakpura Road                273
                             ...
Tindlu                         11
Marsur                         11
2nd Phase Judicial Layout      11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

In [215]:
df.describe()

         total_sqft          bath         price           bhk  PricePerSqFt
count  13274.000000  13247.000000  13320.000000  13320.000000  1.327400e+04
mean    1559.626694      2.692610    112.565627      2.802778  7.907501e+03
std     1238.405258      1.341458    148.971674      1.294496  1.064296e+05
min        1.000000      1.000000      8.000000      1.000000  2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000  4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000  5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000  7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000  1.200000e+07

In [216]:
(df.total_sqft/df.bhk).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [217]:
df = df[(df.total_sqft/df.bhk)>=300]
df.describe()

         total_sqft          bath         price           bhk   PricePerSqFt
count  12530.000000  12457.000000  12530.000000  12530.000000   12530.000000
mean    1594.564544      2.562816    111.382401      2.650838    6303.979357
std     1261.271296      1.080239    152.077329      0.976678    4162.237981
min      300.000000      1.000000      8.440000      1.000000     267.829813
25%     1116.000000      2.000000     49.000000      2.000000    4210.526316
50%     1300.000000      2.000000     70.000000      3.000000    5294.117647
75%     1700.000000      3.000000    115.000000      3.000000    6916.666667
max    52272.000000     16.000000   3600.000000     16.000000  176470.588235

In [218]:
df.PricePerSqFt.describe()

count     12530.000000
mean       6303.979357
std        4162.237981
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: PricePerSqFt, dtype: float64

In [219]:
def remove_outlier_sqft(df):
    df_op = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        m = np.mean(subdf.PricePerSqFt)
        sd= np.std(subdf.PricePerSqFt)
        gen_df = subdf[(subdf.PricePerSqFt>(m-sd)) & (subdf.PricePerSqFt<=(m+sd))]
        df_op = pd.concat([df_op, gen_df], ignore_index=True)
    return df_op

df = remove_outlier_sqft(df)
df.describe()

         total_sqft         bath         price           bhk  PricePerSqFt
count  10301.000000  10245.00000  10301.000000  10301.000000  10301.000000
mean    1508.440608      2.47428     91.286372      2.574896   5659.062876
std      880.694214      0.98150     86.342786      0.897649   2265.774749
min      300.000000      1.00000     10.000000      1.000000   1250.000000
25%     1110.000000      2.00000     49.000000      2.000000   4244.897959
50%     1286.000000      2.00000     67.000000      2.000000   5175.600739
75%     1650.000000      3.00000    100.000000      3.000000   6428.571429
max    30400.000000     16.00000   2200.000000     16.000000  24509.803922

In [220]:
def bhk_outlier_remover(df):
    exclude_index = np.array([])
    for loc, loc_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in loc_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean':np.mean(bhk_df.PricePerSqFt),
                'sd':np.std(bhk_df.PricePerSqFt),
                'cnt':bhk_df.shape[0]
            }
        print(loc, bhk_stats)
        for bhk, bhk_df in loc_df.groupby('bhk'):
            stats = bhk_stats.get(bhk-1)
            if stats and stats['cnt']>5:
                exclude_index = np.append(exclude_index, bhk_df[bhk_df.PricePerSqFt<stats['mean']].index.values)
    return df.drop(exclude_index, axis = 'index')

In [221]:
df = bhk_outlier_remover(df)
df

1st Block Jayanagar {2: {'mean': np.float64(11983.805668016194), 'sd': np.float64(0.0), 'cnt': 1}, 3: {'mean': np.float64(11756.16905248807), 'sd': np.float64(701.6243657657865), 'cnt': 3}, 4: {'mean': np.float64(15018.711280365416), 'sd': np.float64(1.2278182423353805), 'cnt': 3}}
1st Phase JP Nagar {1: {'mean': np.float64(5952.380952380952), 'sd': np.float64(0.0), 'cnt': 1}, 2: {'mean': np.float64(7931.806799837383), 'sd': np.float64(1534.1422783514056), 'cnt': 8}, 3: {'mean': np.float64(9151.192151725822), 'sd': np.float64(1054.731726021645), 'cnt': 7}, 4: {'mean': np.float64(7537.92218148637), 'sd': np.float64(1607.0591069513537), 'cnt': 3}, 5: {'mean': np.float64(5666.666666666667), 'sd': np.float64(0.0), 'cnt': 1}}
2nd Phase Judicial Layout {2: {'mean': np.float64(3851.8518518518517), 'sd': np.float64(497.593660834978), 'cnt': 3}, 3: {'mean': np.float64(3620.93991671624), 'sd': np.float64(241.87983343248052), 'cnt': 5}}
2nd Stage Nagarbhavi {4: {'mean': np.float64(15891.203703703704), 'sd': np.float64(1668.9846920398563), 'cnt': 4}, 6: {'mean': np.float64(16891.666666666668), 'sd': np.float64(1858.333333333333), 'cnt': 2}}
5th Block Hbr Layout {2: {'mean': np.float64(4755.410708222867), 'sd': np.float64(374.06419031565235), 'cnt': 3}, 3: {'mean': np.float64(5511.811023622047), 'sd': np.float64(0.0), 'cnt': 1}, 5: {'mean': np.float64(3611.1111111111113), 'sd': np.float64(0.0), 'cnt': 1}, 6: {'mean': np.float64(5882.35294117647), 'sd': np.float64(0.0), 'cnt': 1}}
5th Phase JP Nagar {1: {'mean': np.float64(4628.623188405797), 'sd': np.float64(371.376811594203), 'cnt': 2}, 2: {'mean': np.float64(5067.359785883266), 'sd': np.float64(453.24956183513086), 'cnt': 17}, 3: {'mean': np.float64(5112.892626961968), 'sd': np.float64(526.8794907246175), 'cnt': 8}, 5: {'mean': np.float64(4325.0), 'sd': np.float64(75.0), 'cnt': 2}}
6th Phase JP Nagar {2: {'mean': np.float64(5932.976565810137), 'sd': np.float64(671.9347030151997), 'cnt': 8}, 3: {'mean': np.float64(8403.2863080867), 'sd': np.float64(1515.4146231166221), 'cnt': 5}, 4: {'mean': np.float64(7704.160246533128), 'sd': np.float64(0.0), 'cnt': 1}}
7th Phase JP Nagar {1: {'mean': np.float64(6133.333333333334), 'sd': np.float64(133.33333333333348), 'cnt': 2}, 2: {'mean': np.float64(6272.516842644273), 'sd': np.float64(1012.7881476778178), 'cnt': 40}, 3: {'mean': np.float64(6612.861682598103), 'sd': np.float64(1181.6582893458344), 'cnt': 57}, 4: {'mean': np.float64(6028.22068063778), 'sd': np.float64(1482.7661351832348), 'cnt': 2}}
8th Phase JP Nagar {1: {'mean': np.float64(6357.427937915743), 'sd': np.float64(267.1694064501245), 'cnt': 4}, 2: {'mean': np.float64(4324.406715739656), 'sd': np.float64(1131.8308808521078), 'cnt': 22}, 3: {'mean': np.float64(4293.744876160689), 'sd': np.float64(723.4267508470379), 'cnt': 17}, 4: {'mean': np.float64(4539.6147062813725), 'sd': np.float64(195.35428340140427), 'cnt': 3}, 5: {'mean': np.float64(4335.260115606937), 'sd': np.float64(0.0), 'cnt': 1}}
9th Phase JP Nagar {1: {'mean': np.float64(3333.3333333333335), 'sd': np.float64(0.0), 'cnt': 1}, 2: {'mean': np.float64(4653.05138390364), 'sd': np.float64(834.4408302683471), 'cnt': 20}, 3: {'mean': np.float64(4518.339436369508), 'sd': np.float64(790.2476753262926), 'cnt': 9}, 4: {'mean': np.float64(5336.8421052631575), 'sd': np.float64(800.5999597024291), 'cnt': 3}}
AECS Layout {2: {'mean': np.float64(4921.300339526721), 'sd': np.float64(619.6355499375203), 'cnt': 7}, 3: {'mean': np.float64(4500.0), 'sd': np.float64(0.0), 'cnt': 1}}
Abbigere {1: {'mean': np.float64(3310.9205535075066), 'sd': np.float64(610.6480739434737), 'cnt': 2}, 2: {'mean': np.float64(4058.165803016323), 'sd': np.float64(62.235187280114864), 'cnt': 13}, 3: {'mean': np.float64(3571.4285714285716), 'sd': np.float64(0.0), 'cnt': 1}, 6: {'mean': np.float64(3165.4545454545455), 'sd': np.float64(74.5454545454545), 'cnt': 2}, 8: {'mean': np.float64(5000.0), 'sd': np.float64(0.0), 'cnt': 1}}
Akshaya Nagar {2: {'mean': np.float64(4781.22783734999), 'sd': np.float64(453.10974836521865), 'cnt': 17}, 3: {'mean': np.float64(5294.361032273932), 'sd': np.float64(513.4396107693667), 'cnt': 30}}
Ambalipura {1: {'mean': np.float64(5690.909090909091), 'sd': np.float64(0.0), 'cnt': 1}, 2: {'mean': np.float64(5886.737386783397), 'sd': np.float64(736.0640513407117), 'cnt': 10}, 3: {'mean': np.float64(6331.134555298749), 'sd': np.float64(569.718562351169), 'cnt': 7}, 4: {'mean': np.float64(5503.386809269163), 'sd': np.float64(339.75044563279835), 'cnt': 2}}
Ambedkar Nagar {2: {'mean': np.float64(6454.091928430547), 'sd': np.float64(182.0843219299883), 'cnt': 5}, 3: {'mean': np.float64(6572.746532916982), 'sd': np.float64(422.13464472691317), 'cnt': 19}, 4: {'mean': np.float64(7684.086312870249), 'sd': np.float64(531.2111375546801), 'cnt': 2}}
Amruthahalli {1: {'mean': np.float64(4020.618556701031), 'sd': np.float64(0.0), 'cnt': 1}, 2: {'mean': np.float64(4953.838379629301), 'sd': np.float64(823.6966143070669), 'cnt': 12}, 3: {'mean': np.float64(5574.846418310635), 'sd': np.float64(1077.4444900329127), 'cnt': 7}}
Anandapura {2: {'mean': np.float64(4335.741837049203), 'sd': np.float64(710.6695705040866), 'cnt': 14}, 3: {'mean': np.float64(4376.900862764794), 'sd': np.float64(811.4741024839058), 'cnt': 5}, 4: {'mean': np.float64(5145.797598627787), 'sd': np.float64(0.0), 'cnt': 1}}
Ananth Nagar {1: {'mean': np.float64(2800.0), 'sd': np.float64(0.0), 'cnt': 4}, 2: {'mean': np.float64(3015.4242497371583), 'sd': np.float64(491.5389870277812), 'cnt': 19}, 3: {'mean': np.float64(3239.9055148973916), 'sd': np.float64(333.6052126335633), 'cnt': 3}}
Anekal {1: {'mean': np.float64(3307.549188983317), 'sd': np.float64(602.8526665064047), 'cnt': 6}, 2: {'mean': np.float64(3418.531131818201), 'sd': np.float64(543.1514964904059), 'cnt': 22}, 3: {'mean': np.float64(4075.680581158921), 'sd': np.float64(340.19143395777115), 'cnt': 4}, 4: {'mean': np.float64(3000.0), 'sd': np.float64(0.0), 'cnt': 1}}
Anjanapura {2: {'mean': np.float64(3451.5654968214635), 'sd': np.float64(402.7964034804156), 'cnt': 7}, 3: {'mean': np.float64(4783.11324361657), 'sd': np.float64(2019.9576386770505), 'cnt': 4}, 4: {'mean': np.float64(3852.102102102102), 'sd': np.float64(796.5465465465463), 'cnt': 2}}
Ardendale {2: {'mean': np.float64(5596.405228758171), 'sd': np.float64(122.54901960784309), 'cnt': 2}, 3: {'mean': np.float64(5378.1844320453965), 'sd': np.float64(324.88136834734956), 'cnt': 10}, 4: {'mean': np.float64(6445.687085352693), 'sd': np.float64(663.0498079730814), 'cnt': 7}}
Arekere {1: {'mean': np.float64(4666.666666666667), 'sd': np.float64(0.0), 'cnt': 1}, 2: {'mean': np.float64(4884.730750645279), 'sd': np.float64(371.1132245946985), 'cnt': 6}, 3: {'mean': np.float64(5822.747277384037), 'sd': np.float64(695.6480303741811), 'cnt': 3}, 4: {'mean': np.float64(5239.852398523985), 'sd': np.float64(0.0), 'cnt': 1}}
Attibele {1: {'mean': np.float64(2823.0512983538965), 'sd': np.float64(440.8851261837879), 'cnt': 18}, 2: {'mean': np.float64(3204.1609520225234), 'sd': np.float64(617.2070386969107), 'cnt': 12}, 3: {'mean': np.float64(4330.95861895704), 'sd': np.float64(1307.8696742735906), 'cnt': 4}, 4: {'mean': np.float64(3840.959409594096), 'sd': np.float64(540.9594095940961), 'cnt': 2}}
BEML Layout {2: {'mean': np.float64(5944.048212904286), 'sd': np.float64(1628.8084083258766), 'cnt': 6}, 3: {'mean': np.float64(4250.0), 'sd': np.float64(0.0), 'cnt': 4}, 5: {'mean': np.float64(9375.0), 'sd': np.float64(0.0), 'cnt': 1}}
BTM 2nd Stage {2: {'mean': np.float64(5621.791028153005), 'sd': np.float64(795.7682556051348), 'cnt': 14}, 3: {'mean': np.float64(10282.08598547458), 'sd': np.float64(3831.7704948598844), 'cnt': 9}, 5: {'mean': np.float64(13913.04347826087), 'sd': np.float64(0.0), 'cnt': 1}}
BTM Layout {1: {'mean': np.float64(4444.444444444444), 'sd': np.float64(0.0), 'cnt': 1}, 2: {'mean': np.float64(5073.776447337828), 'sd': np.float64(424.90705275056126), 'cnt': 4}, 3: {'mean': np.float64(5685.2029893641175), 'sd': np.float64(881.6401846985812), 'cnt': 7}, 6: {'mean': np.float64(5000.0), 'sd': np.float64(0.0), 'cnt': 1}}
Babusapalaya {2: {'mean': np.float64(3799.9594889549185), 'sd': np.float64(423.8304869618116), 'cnt': 11}, 3: {'mean': np.float64(3669.941030877054), 'sd': np.float64(601.932707346431), 'cnt': 10}}
Badavala Nagar {2: {'mean': np.float64(6357.9277864992155), 'sd': np.float64(0.0), 'cnt': 2}, 3: {'mean': np.float64(6279.828480978357), 'sd': np.float64(42.27887875035828), 'cnt': 7}}
Balagere {1: {'mean': np.float64(5865.01000449379), 'sd': np.float64(539.315075028032), 'cnt': 9}, 2: {'mean': np.float64(6191.495143186286), 'sd': np.float64(543.3822583816924), 'cnt': 28}}
Banashankari {1: {'mean': np.float64(8333.333333333334), 'sd': np.float64(0.0), 'cnt': 2}, 2: {'mean': np.float64(5038.253269278571), 'sd': np.float64(1168.5163463486567), 'cnt': 31}, 3: {'mean': np.float64(5817.282245183152), 'sd': np.float64(1663.833391137828), 'cnt': 29}, 4: {'mean': np.float64(3800.0), 'sd': np.float64(0.0), 'cnt': 1}}
Banashankari Stage II {2: {'mean': np.float64(8701.636799298034), 'sd': np.float64(1030.287972433991), 'cnt': 4}, 3: {'mean': np.float64(10723.280423280425), 'sd': np.float64(4231.90962768462), 'cnt': 6}, 4: {'mean': np.float64(12500.0), 'sd': np.float64(0.0), 'cnt': 1}, 5: {'mean': np.float64(18214.285714285714), 'sd': np.float64(3035.7142857142853), 'cnt': 2}}
Banashankari Stage III {2: {'mean': np.float64(5430.250387687147), 'sd': np.float64(1871.4365421808766), 'cnt': 4}, 3: {'mean': np.float64(5330.43635317069), 'sd': np.float64(1014.1370099612311), 'cnt': 10}, 4: {'mean': np.float64(7333.333333333333), 'sd': np.float64(2054.8046676563254), 'cnt': 3}, 6: {'mean': np.float64(5000.0), 'sd': np.float64(0.0), 'cnt': 1}}
Banashankari Stage V {2: {'mean': np.float64(3983.4541062801936), 'sd': np.float64(527.4154589371976), 'cnt': 2}, 3: {'mean': np.float64(3581.57134026118), 'sd': np.float64(544.8260330690271), 'cnt': 9}}
Banashankari Stage VI {2: {'mean': np.float64(5072.0195454829345), 'sd': np.float64(22.81429179660186), 'cnt': 3}, 3: {'mean': np.float64(5006.925310122253), 'sd': np.float64(23.924063833179062), 'cnt': 3}, 4: {'mean': np.float64(5041.801948051948), 'sd': np.float64(2237.063491984229), 'cnt': 4}}
Banaswadi {1: {'mean': np.float64(6641.366223908918), 'sd': np.float64(0.0), 'cnt': 1}, 2: {'mean': np.float64(5110.715347907356), 'sd': np.float64(582.5694084547944), 'cnt': 10}, 3: {'mean': np.float64(4656.25), 'sd': np.float64(0.0), 'cnt': 1}, 5: {'mean': np.float64(7356.8050446663165), 'sd': np.float64(0.0), 'cnt': 1}}
Banjara Layout {2: {'mean': np.float64(6635.496110794916), 'sd': np.float64(905.9365352849989), 'cnt': 3}, 3: {'mean': np.float64(5600.0), 'sd': np.float64(0.0), 'cnt': 1}}
Bannerghatta {2: {'mean': np.float64(6630.037324398989), 'sd': np.float64(872.6962508901346), 'cnt': 4}, 3: {'mean': np.float64(7565.595658950089), 'sd': np.float64(786.4254337865935), 'cnt': 4}, 4: {'mean': np.float64(8398.03739052883), 'sd': np.float64(97.90458840399697), 'cnt': 2}}
Bannerghatta Road {1: {'mean': np.float64(4932.455648926237), 'sd': np.float64(741.987966876004), 'cnt': 5}, 2: {'mean': np.float64(5156.722324231199), 'sd': np.float64(951.851933786921), 'cnt': 59}, 3: {'mean': np.float64(5384.498056381959), 'sd': np.float64(1219.6689012468119), 'cnt': 71}, 4: {'mean': np.float64(5968.786895986739), 'sd': np.float64(1737.4673135012401), 'cnt': 8}, 5: {'mean': np.float64(5851.851851851852), 'sd': np.float64(0.0), 'cnt': 1}, 6: {'mean': np.float64(8108.108108108108), 'sd': np.float64(0.0), 'cnt': 1}}
Basavangudi {2: {'mean': np.float64(9700.42512839123), 'sd': np.float64(665.8646001174526), 'cnt': 6}, 3: {'mean': np.float64(9210.853069429275), 'sd': np.float64(904.4272935920624), 'cnt': 10}, 4: {'mean': np.float64(10095.80105992662), 'sd': np.float64(95.80105992662084), 'cnt': 2}}
Basaveshwara Nagar {2: {'mean': np.float64(6750.0), 'sd': np.float64(552.7707983925667), 'cnt': 5}, 3: {'mean': np.float64(7834.767884859602), 'sd': np.float64(59.968957245661386), 'cnt': 2}, 5: {'mean': np.float64(11069.444444444445), 'sd': np.float64(1847.2222222222217), 'cnt': 2}}
Battarahalli {2: {'mean': np.float64(4345.7243068848575), 'sd': np.float64(823.6340914029164), 'cnt': 9}, 3: {'mean': np.float64(5015.40017552159), 'sd': np.float64(337.7428143761158), 'cnt': 8}}
Begur {2: {'mean': np.float64(4961.668185533498), 'sd': np.float64(39.10751993914706), 'cnt': 3}, 3: {'mean': np.float64(4510.654979278204), 'sd': np.float64(599.1143016556773), 'cnt': 9}, 4: {'mean': np.float64(3906.25), 'sd': np.float64(0.0), 'cnt': 1}}
Begur Road {2: {'mean': np.float64(3624.166282880882), 'sd': np.float64(262.3730178311292), 'cnt': 35}, 3: {'mean': np.float64(3684.8720181009558), 'sd': np.float64(378.82522322146735), 'cnt': 28}, 4: {'mean': np.float64(4787.9894501927365), 'sd': np.float64(0.0), 'cnt': 1}}
Bellandur {1: {'mean': np.float64(4210.526315789473), 'sd': np.float64(0.0), 'cnt': 1}, 2: {'mean': np.float64(5116.644099551324), 'sd': np.float64(1016.3979870126873), 'cnt': 52}, 3: {'mean': np.float64(5647.571810653258), 'sd': np.float64(1127.9673046785176), 'cnt': 31}, 4: {'mean': np.float64(6759.122130530177), 'sd': np.float64(845.9579630611066), 'cnt': 4}}
Benson Town {2: {'mean': np.float64(12686.709975197631), 'sd': np.float64(3611.8164390019756), 'cnt': 4}, 3: {'mean': np.float64(14313.731148045554), 'sd': np.float64(2420.56421489562), 'cnt': 3}, 4: {'mean': np.float64(14856.497304850036), 'sd': np.float64(282.5062734599014), 'cnt': 2}}
Bharathi Nagar {2: {'mean': np.float64(4813.740209190311), 'sd': np.float64(471.43026983759114), 'cnt': 8}, 3: {'mean': np.float64(4200.120192307692), 'sd': np.float64(0.0), 'cnt': 1}}
Bhoganhalli {2: {'mean': np.float64(5417.416718889453), 'sd': np.float64(285.36806332317167), 'cnt': 12}, 3: {'mean': np.float64(6125.4200445093), 'sd': np.float64(899.1112373435706), 'cnt': 13}, 4: {'mean': np.float64(5777.756745789307), 'sd': np.float64(871.3161320532748), 'cnt': 11}}
Billekahalli {2: {'mean': np.float64(5962.1264143650205), 'sd': np.float64(952.8379048046246), 'cnt': 7}, 3: {'mean': np.float64(6179.829109009818), 'sd': np.float64(1029.8742088847782), 'cnt': 6}}
Binny Pete {1: {'mean': np.float64(8034.164957849169), 'sd': np.float64(901.878395083154), 'cnt': 4}, 2: {'mean': np.float64(7933.924709828325), 'sd': np.float64(1003.8042279006136), 'cnt': 2}, 3: {'mean': np.float64(8471.722137179819), 'sd': np.float64(951.1093605219069), 'cnt': 6}, 4: {'mean': np.float64(8382.135462880804), 'sd': np.float64(1141.674060928719), 'cnt': 2}}
Bisuvanahalli {2: {'mean': np.float64(3863.8012733035357), 'sd': np.float64(405.2872025065846), 'cnt': 12}, 3: {'mean': np.float64(4006.5825354643744), 'sd': np.float64(468.0230389083769), 'cnt': 31}}
Bommanahalli {1: {'mean': np.float64(4302.184466019417), 'sd': np.float64(552.1844660194174), 'cnt': 2}, 2: {'mean': np.float64(4544.41960101665), 'sd': np.float64(569.7400942075514), 'cnt': 9}, 3: {'mean': np.float64(4254.328104328105), 'sd': np.float64(505.922183603648), 'cnt': 4}, 4: {'mean': np.float64(4047.6190476190477), 'sd': np.float64(0.0), 'cnt': 1}, 8: {'mean': np.float64(4666.666666666667), 'sd': np.float64(0.0), 'cnt': 1}}
Bommasandra {2: {'mean': np.float64(3813.947572153106), 'sd': np.float64(244.236658864445), 'cnt': 19}, 3: {'mean': np.float64(3815.8530659565145), 'sd': np.float64(403.8116627539011), 'cnt': 11}}
Bommasandra Industrial Area {2: {'mean': np.float64(2887.892987573868), 'sd': np.float64(0.47920744469383775), 'cnt': 11}, 3: {'mean': np.float64(2863.160206574431), 'sd': np.float64(59.9654742104211), 'cnt': 7}}
Bommenahalli {3: {'mean': np.float64(8565.382032363164), 'sd': np.float64(1314.9620051314946), 'cnt': 3}, 4: {'mean': np.float64(8564.836466843257), 'sd': np.float64(717.6221010374835), 'cnt': 6}}
Brookefield {2: {'mean': np.float64(5837.492693390221), 'sd': np.float64(903.6255944977522), 'cnt': 19}, 3: {'mean': np.float64(5795.407173862258), 'sd': np.float64(1201.0625471599164), 'cnt': 13}, 4: {'mean': np.float64(6680.252598242926), 'sd': np.float64(2089.3417875296827), 'cnt': 7}, 5: {'mean': np.float64(8974.358974358975), 'sd': np.float64(0.0), 'cnt': 1}}
Budigere {1: {'mean': np.float64(5155.722891566265), 'sd': np.float64(166.41859289793305), 'cnt': 4}, 2: {'mean': np.float64(5034.160717791254), 'sd': np.float64(199.1459774106948), 'cnt': 23}, 3: {'mean': np.float64(4995.782145950289), 'sd': np.float64(304.7321376982579), 'cnt': 22}}
CV Raman Nagar {1: {'mean': np.float64(7092.198581560284), 'sd': np.float64(0.0), 'cnt': 1}, 2: {'mean': np.float64(5155.724160108177), 'sd': np.float64(750.6157631590067), 'cnt': 18}, 3: {'mean': np.float64(5069.1182815641005), 'sd': np.float64(895.7302193450797), 'cnt': 8}}
Chamrajpet {1: {'mean': np.float64(16831.68316831683), 'sd': np.float64(0.0), 'cnt': 1}, 2: {'mean': np.float64(9792.423102012144), 'sd': np.float64(3818.3998448404645), 'cnt': 5}, 3: {'mean': np.float64(7141.805995187703), 'sd': np.float64(751.0857983228121), 'cnt': 3}, 4: {'mean': np.float64(10827.574839290468), 'sd': np.float64(1880.2064182378372), 'cnt': 2}}
Chandapura {1: {'mean': np.float64(2520.6090114704184), 'sd': np.float64(140.1570055608275), 'cnt': 19}, 2: {'mean': np.float64(2822.6938747446193), 'sd': np.float64(410.55761448180084), 'cnt': 37}, 3: {'mean': np.float64(2853.1236984866746), 'sd': np.float64(427.653808367682), 'cnt': 26}, 4: {'mean': np.float64(3498.942358540455), 'sd': np.float64(0.0), 'cnt': 1}}
Channasandra {2: {'mean': np.float64(3613.5088756107493), 'sd': np.float64(502.50868004330425), 'cnt': 24}, 3: {'mean': np.float64(4500.644242719408), 'sd': np.float64(1005.213241509808), 'cnt': 9}, 4: {'mean': np.float64(5963.333333333333), 'sd': np.float64(0.0), 'cnt': 1}, 6: {'mean': np.float64(4285.714285714285), 'sd': np.float64(0.0), 'cnt': 1}}
Chikka Tirupathi {3: {'mean': np.float64(4090.4654941407116), 'sd': np.float64(246.87536752515462), 'cnt': 4}, 4: {'mean': np.float64(4568.837506464278), 'sd': np.float64(449.90860011916783), 'cnt': 7}}
Chikkabanavar {2: {'mean': np.float64(3979.526682999282), 'sd': np.float64(296.21104114438486), 'cnt': 3}, 3: {'mean': np.float64(4242.424242424242), 'sd': np.float64(757.5757575757575), 'cnt': 2}, 4: {'mean': np.float64(3252.032520325203), 'sd': np.float64(0.0), 'cnt': 1}, 5: {'mean': np.float64(3645.833333333333), 'sd': np.float64(395.83333333333326), 'cnt': 2}, 8: {'mean': np.float64(2750.0), 'sd': np.float64(0.0), 'cnt': 1}}
Chikkalasandra {2: {'mean': np.float64(4680.665935758178), 'sd': np.float64(906.7207027292568), 'cnt': 14}, 3: {'mean': np.float64(4209.541795721919), 'sd': np.float64(468.54274526277595), 'cnt': 14}}
Choodasandra {2: {'mean': np.float64(4782.163531612381), 'sd': np.float64(528.754856051744), 'cnt': 12}, 3: {'mean': np.float64(4993.1936034011), 'sd': np.float64(599.6867241072546), 'cnt': 10}, 4: {'mean': np.float64(8645.533141210375), 'sd': np.float64(0.0), 'cnt': 1}}
Cooke Town {2: {'mean': np.float64(9450.335685771604), 'sd': np.float64(1592.310446826406), 'cnt': 3}, 3: {'mean': np.float64(11852.598087462115), 'sd': np.float64(1661.385526814624), 'cnt': 4}, 4: {'mean': np.float64(11016.71535215839), 'sd': np.float64(375.6897111327489), 'cnt': 2}}
Cox Town {2: {'mean': np.float64(8230.365020192607), 'sd': np.float64(2084.870283562963), 'cnt': 5}, 3: {'mean': np.float64(7780.757079649942), 'sd': np.float64(1186.6163940265649), 'cnt': 4}}
Cunningham Road {3: {'mean': np.float64(19562.042390433755), 'sd': np.float64(1371.6473545157753), 'cnt': 8}, 4: {'mean': np.float64(22399.47110781565), 'sd': np.float64(2068.0898222124456), 'cnt': 3}}
Dasanapura {1: {'mean': np.float64(5790.960451977401), 'sd': np.float64(0.0), 'cnt': 1}, 2: {'mean': np.float64(5113.831187981814), 'sd': np.float64(479.0067310357899), 'cnt': 7}, 3: {'mean': np.float64(5032.659409020218), 'sd': np.float64(255.05443234836684), 'cnt': 2}}

,location,size,total_sqft,bath,price,bhk,PricePerSqFt
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333
3,1st Block Jayanagar,3 BHK,1200.0,2.0,130.0,3,10833.333333
4,1st Block Jayanagar,2 BHK,1235.0,2.0,148.0,2,11983.805668
...,...,...,...,...,...,...,...
10292,other,2 BHK,1200.0,2.0,70.0,2,5833.333333
10293,other,1 BHK,1800.0,1.0,200.0,1,11111.111111
10296,other,2 BHK,1353.0,2.0,110.0,2,8130.081301
10297,other,1 Bedroom,812.0,1.0,26.0,1,3201.970443
10300,other,4 BHK,3600.0,5.0,400.0,4,11111.111111

In [222]:
df.drop(columns=['size','PricePerSqFt'], inplace= True)

In [223]:
df.head(3)

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3

In [224]:
df = df.dropna()

In [225]:
x = df.drop(columns='price')
y = df.price

In [226]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [227]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25, random_state=42)

In [228]:
column_tran = make_column_transformer((OneHotEncoder(),
                                       ['location']),
                                      remainder='passthrough' )

In [229]:
scaler = StandardScaler()

In [230]:
lr = LinearRegression()
pipe = make_pipeline(column_tran, lr)
pipe.fit(x_train, y_train)
pred_lr = pipe.predict(x_test)
r2_score(y_test, pred_lr)

0.8440473590581072

In [231]:
lasso = Lasso()
pipe = make_pipeline(column_tran, lasso)
pipe.fit(x_train, y_train)
pred_lasso = pipe.predict(x_test)
r2_score(y_test, pred_lasso)

0.6819751942873677

In [232]:
ridge = Ridge()
pipe = make_pipeline(column_tran, ridge)
pipe.fit(x_train, y_train)
pred_ridge = pipe.predict(x_test)
r2_score(y_test, pred_ridge)

0.6706185172124454